baseURL = "https://batuking1111.github.io/"
locale = 'en-us'
title = "Batuhan Personal Blog"
theme = "stack"
[params]
    mainSections = ["post"]
    featuredImageField = "image"

    [[menu.social]]
      name = "GitHub"
      url  = "https://github.com/Batuking1111"
      params = { Icon = "brand-github", newTab = true }

    [[menu.social]]
      name = "Alpha Ray Corp"
      url  = "https://github.com/alpharaycorp"
      params = { Icon = "brand-github", newTab = true }

    [[menu.social]]
      name = "LinkedIn"
      url  = "https://www.linkedin.com/in/batuhanerkann/"
      params = { Icon = "brand-linkedin", newTab = true }