baseURL = "https://batuking1111.github.io/"
locale = 'en-us'
title = "Batuhan Personal Blog"
theme = "stack"
[params]
    mainSections = ["post"]
    featuredImageField = "image"

    [params.sidebar]
      avatar = "img/avatar.jpg"

    [[menu.social]]
      name = "GitHub"
      url  = "https://github.com/Batuking1111"
      params = { Icon = "brand-github", newTab = true }

    [[menu.social]]
      name = "Alpha Ray Corp"
      url  = "https://github.com/alpharaycorp"
      params = { Icon = "brand-github", newTab = true }

    [[menu.social]]
      name = "LinkedIn"
      url  = "https://www.linkedin.com/in/batuhanerkann/"
      params = { Icon = "link", newTab = true }

    [[menu.main]]
      name = "Home"
      url = "/"
      weight = 1

    [[menu.main]]
      name = "Archives"
      url = "/archives/"
      weight = 2

    [[menu.main]]
      name = "Search"
      url = "/search/"
      weight = 3

    # -- Widgets: make each widget an object with a `type` field so the partial can access `.type` --
    [params.widgets]
      homepage = [
        { type = "search" },
        { type = "archives" },
        { type = "categories" },
        { type = "tag-cloud" }
      ]

[taxonomies]
  category = "categories"
  tag = "tags"
